services:
  labeler:
    # entrypoint: ./list-labeler
    ports:
      - "${ADMIN_ADDR:-127.0.0.1:12001}:12001"
    command: [
      "--config=/config.yaml",
      "--log-level=0",
      "--listen-addr=:12000",
      "--admin-addr=:12001",
    ]
