# Path to the database file. Required.
# The file will be created if it doesn't exist yet.
sqlite_db: /data/labels.sqlite

# If you have a Bolt database from a previous version, you can specify it here
# and on the first run it will be automatically migrated into SQLite.
# db_file: /data/labels.bolt

# Label signing key. Required.
# Same as with Ozone, generate with: openssl ecparam --name secp256k1 --genkey --noout --outform DER | tail --bytes=+8 | head --bytes=32 | xxd --plain --cols 32
private_key:

# Labeler's DID. Optional.
# If not set, must be provided in each labeling request.
did:

# Labeler doesn't necessarily need to know your label definitions, it will happily
# apply any label you tell it to. But if you do provide them, it will return an error
# if you try to apply an unknown label. It also can update your labeler profile info,
# if you also specify a password below.
labels:
  # The labeler automatically adds identifiers from labelvaluedefinitions to labelvalues,
  # if they're not listed.
  # This means that most of the time you can completely omit specifying labelvalues.
  # Note that all field names are lowercased. This is due to how YAML parsing library
  # handles field names by default.
  labelvalues:
    - dmca-violation
  labelvaluedefinitions:
  # For reference see https://github.com/bluesky-social/atproto/blob/main/lexicons/com/atproto/label/defs.json#L78
    - identifier: elder
      severity: alert
      blurs: none
      defaultsetting: warn
      adultonly: true
      locales:
        - lang: en
          name: Bluesky Elder
          description: 'Warning: Bluesky Elder'

# Stuff below is only required for updating your label definitions
# and signing key in PLC. `did` field above should be provided too.
password:
endpoint:

# Used only by list-labeler. Labeled accounts will be kept in sync with the list.
lists:
  elder: "at://.../app.bsky.graph.list/..."
